# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1s
        max-idle: 200
  datasource:
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  level:
    com.rabbitmq.mapper: debug
