version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ Management UI
#    volumes:
#      - ./libs:/opt/rabbitmq/plugins/
    environment:
      RABBITMQ_PLUGINS: rabbitmq_delayed_message_exchange
    #command: rabbitmq-plugins enable rabbitmq_delayed_message_exchange
