version: '3'

services:
  spring-redis:
    image: redis:latest
    container_name: spring-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - spring-redis
    networks:
      - app-network
networks:
  app-network:
    driver: bridge